name: easy_dart_jwt
description: A simple JWT library in Dart.
version: 0.3.0

repository: https://github.com/AlanMet/jwt

environment:
  sdk: ^3.7.0

dependencies:
  crypto: ^3.0.6
  convert: ^3.0.0
  pointycastle: ^3.0.0
  basic_utils: ^3.6.0

dev_dependencies:
  test: ^1.24.0